class TrackingEvents:
    PRODUCT_PAGE_SEEN = "PRODUCT_PAGE_SEEN"
    PRODUCT_CHECKOUT_CLICKED = "PRODUCT_CHECKOUT_CLICKED"
    STRIPE_API_CALLED_FOR_PAYMENT_LINK = "STRIPE_API_CALLED_FOR_PAYMENT_LINK"
    STRIPE_API_CALLED_FOR_PAYMENT_LINK_RESPONSE = "STRIPE_API_CALLED_FOR_PAYMENT_LINK_RESPONSE"
    STRIPE_PAYMENT_SUCCESS = "STRIPE_PAYMENT_SUCCESS"
    STRIPE_PAYMENT_FAILED = "STRIPE_PAYMENT_FAILED"
    STRIPE_WEBHOOK_FEEDBACK_RECEIVED = "STRIPE_WEBHOOK_FEEDBACK_RECEIVED"

