# Generated by Django 4.2.16 on 2024-09-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0002_alter_paymentlink_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlink',
            name='session_id',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentlink',
            name='payment_url',
            field=models.URLField(),
        ),
    ]
