# Generated by Django 4.2.16 on 2024-09-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0003_paymentlink_session_id_alter_paymentlink_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_time',
            field=models.IntegerField(default=24),
        ),
    ]
